name: ğŸ‘® check norminette and compile flags

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - dev # main <- dev

jobs:
  check-norminette:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ğŸ›’ Install 42-norminette
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install --upgrade norminette

      - name: ğŸ‘® Run norminette
        run: norminette .

  check-compile-flags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ğŸ›’ Install gcc and make
        run: sudo apt-get install -y gcc make
      
      - name: ğŸ‘® Run make
        run: make
